__default__:
  # exchange <staff> with your SLURM account id below
  account: staff

  # directories for slurm logs (no need to change these)
  output: "slurm/logs/{rule}.{wildcards}.out"
  error: "slurm/err/{rule}.{wildcards}.err"
