__default__:
  # exchange <staff> with your SLURM account id below
  account: naiss2023-5-110

  # directories for slurm logs (no need to change these)
  output: "slurm/logs/{rule}.{wildcards}.out"
  error: "slurm/err/{rule}.{wildcards}.err"

bowtie_build:
  #constraint: "mem256GB"
  cpus-per-task: 16
  mem: "96000"
