sample_list: "samples.tsv"
assembly_list: "assemblies.tsv"
assembly_dir: "data/assembly"
annotation_dir: "data/annotation"
featurecounts:
  settings: "-t CDS -g ID -M -Q 10 -B -p"
bowtie2:
  settings: "--very-sensitive"
  threads: 10
annotation_dbs:
  - "pfam"
  - "protein-models"
  - "enzymes"
  - "kos"
  - "modules"
  - "pathways"
norm_methods:
  - "CSS"
  - "TMM"
  - "RLE"
# What features/models to use to normalize the metaT abundance by
norm_models:
  pfam-hmmsearch:
    - PF00133 # tRNA synthetases class I (I, L, M and V)
    - PF00448 # SRP54-type protein, GTPase domain
    - PF00587 # tRNA synthetase class II core domain (G, H, P, S and T)
    - PF00750 # tRNA synthetases class I (R)
    - PF00814 # tRNA N6-adenosine threonylcarbamoyltransferase
    - PF01406 # tRNA synthetases class I (C) catalytic domain
    - PF01409 # tRNA synthetases class II core domain (F)
    - PF01926 # 50S ribosome-binding GTPase
    - PF02403 # Seryl-tRNA synthetase N-terminal domain
    - PF02881 # SRP54-type protein, helical bundle domain
    - PF02912 # Aminoacyl tRNA synthetase class II, N-terminal domain
    - PF03483 # B3/B4 tRNA-binding domain
    - PF03484 # tRNA synthetase B5 domain
    - PF03485 # Arginyl tRNA synthetase N terminal domain
    - PF05746 # DALR anticodon binding domain
    - PF06071 # YchF-GTPase C terminal protein domain
    - PF08264 # Aminoacyl tRNA synthetase
    - PF09190 # Aminoacyl tRNA synthetase
    - PF09334 # tRNA synthetases class I (M)
    - PF10458 # Valyl tRNA synthetase tRNA binding arm
    - PF13603 # Leucyl-tRNA synthetase, Domain 2
    - PF17759 # Phenylalanyl tRNA synthetase beta chain CLM domain
    - PF18490 # tRNA-binding domain